---
name: End-to-End Tests

on:
  push:
    branches:
      - master
      - develop
      - duo

  pull_request:
    branches:
      - master
      - develop
      - duo
  schedule:
    - cron: 0 0 * * * # At Midnight Every Day

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Build Docker
        id: docker_build
        run: |
          python setup.py --version
          pip install -r requirements.txt
          pip install -e .
          version=$(armory --version)
          echo "armory --verion -> $version"
          bash docker/build.sh -f all --tag $version --no-cache
    outputs:
      imageTag: ${{ steps.docker_build.version }}
  docker-pytorch-end2end:
    name: Docker Torch End2End
    needs: docker-build
    runs-on: self-hosted
    steps:
      - name: Run Tests Torch Docker
        run: |
          echo "Docker Tag: ${{ needs.docker_build.outputs.imageTag }} "
